import { createRoot } from 'react-dom/client'
import './styles.css'

import { App } from './App'

/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

function Legend() {
  return (
    <div style={{ fontSize: '13px', position: 'absolute', pointerEvents: 'none', top: 0, left: 0, width: '100vw', height: '100vh' }}>
      <div style={{ position: 'absolute', top: 120, left: 40, display: 'flex', flexDirection: 'column', gap: '10px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>
          <div style={{ width: '20px', height: '20px', backgroundColor: 'blue' }}></div>
          <span>Category 1</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>
          <div style={{ width: '20px', height: '20px', backgroundColor: 'yellow' }}></div>
          <span>Category 2</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>
          <div style={{ width: '20px', height: '20px', backgroundColor: 'green' }}></div>
          <span>Category 3</span>
        </div>
      </div>
      <a style={{ position: 'absolute', top: 40, left: 40, fontSize: '13px' }} href="#">
        scroll up/down ...
      </a>
    </div>
  )
}

function Root() {
  return (
    <>
      <App />
      <Legend />
    </>
  )
}

createRoot(document.getElementById('root')).render(<Root />)
